### ISSUE TITLE
Consider removing links to lesson content.

### ISSUE THREAD

**Issue by bsmith89** [ucsf-ckm/2017-07-15-ucsf-python#4]
I prefer that learners not try to follow along with the textual representation of the lesson during the workshop, and I tend to only provide a link to that material after the workshop.

In my experience, having the text of the lesson can be detrimental to the learners' experience either because I deviate from the lesson (and they get caught up in the mismatch), or because they are less willing to ask for help when they think the answers will be easy to find in the materials.

**Comment by gboushey** [comment]
I agree.  I'll remove the links for the python, unix, and github lessons.

What do you think of leaving the reference links in the syllabus?

**Comment by bsmith89** [comment]
Fine by me.  I've never noticed any issues with keeping those.

**Comment by gboushey** [comment]
removed them in 1fdb7be

**Comment by bsmith89** [comment]
Awesome.  Thanks.
