### ISSUE TITLE
Add workshop building and room number to "Workshop Ad" at top of page.

### ISSUE THREAD

**Issue by bsmith89** [ucsf-ckm/2017-07-15-ucsf-python#6]
I like to include the location in bold for learners (and instructors) who are rushing to find the room on the first morning.

No urgency, we can add this in the week before the workshop.

@arieldeardorff Is the room: "Mission Hall rm. 550"?

**Comment by gboushey** [comment]
That certainly describes me the last time I was trying to find the workshop location.  The location is a little harder to find if you're just glancing at the main page.    

Feel free to add this now or when the workshop is closer, thanks.

**Comment by bsmith89** [comment]
Replacing this with a pull request with its own branch.
